spring:
  # 配置数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/forum?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 10086

  #配置redis缓存
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 8 # 连接池中的最大空闲连接

  #配置邮箱
  mail:
    default-encoding: UTF-8
    host: smtp.qiye.aliyun.com
    port: 465
    username: jryyy@angeldevil.top
    password: JrYYY123
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.qiye.aliyun.com
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          auth: true
          starttls:
            enable: true
            required: true

  jackson:
    date-format: yyyy-mm-dd hh:mm:ss
    time-zone: GMT+8
  jpa:
    show-sql: true

#配置端口号
server:
  port: 9896

#图片临时路径
file:
  uploadFolder: D:/home/
  staticAccessPath: /upload/**
  url: http://192.168.19.59:9896/upload/

#token
token:
  effectiveTime: 8640000
  secret: hjijfvbw859

# Logging
logging:
  level:
    root: info
    com:
      quartzenergy:
        ofs: debug

debug: true


