spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/forum?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 10086
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 8 # 连接池中的最大空闲连接
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 1952381587@qq.com
    password: 18397331446plm
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    show-sql: true


mail:
  fromMail:
    addr: JrYYY@Test.com

server:
  port: 9896

debug: true

cds:
  imagesPath: D:\cs\bs\user\avatar
  zoneImages: D:\cs\bs\user\zone

#token
token:
  effectiveTime: 8640000
  secret: hjijfvbw859


# Logging
logging:
  level:
    root: info
    com:
      quartzenergy:
        ofs: debug

